### ISSUE TITLE
Failed to upload file - `401: No Authorization was found in request.cookies`

### ISSUE THREAD

**Issue by adamhl8** [kyantech/Palmr#179]
I just set up Palmr and I'm not able to upload anything. I don't think this is related to file permissions and the default UID and GID of 1000 should be fine in my case.

<img width="630" height="96" alt="Image" src="https://github.com/user-attachments/assets/cbf78b29-876c-4103-bd4b-65f31b2b0125" />

In the container logs:

```
FastifyError [Error]: No Authorization was found in request.cookies
    at lookupToken (/app/palmr-app/node_modules/.pnpm/@fastify+jwt@9.1.0/node_modules/@fastify/jwt/jwt.js:272:17)
    at _Request.requestVerify [as jwtVerify] (/app/palmr-app/node_modules/.pnpm/@fastify+jwt@9.1.0/node_modules/@fastify/jwt/jwt.js:487:15)
    at useGlobalOptions (/app/palmr-app/node_modules/.pnpm/@fastify+jwt@9.1.0/node_modules/@fastify/jwt/jwt.js:455:31)
    at new Promise (<anonymous>)
    at _Request.requestVerify [as jwtVerify] (/app/palmr-app/node_modules/.pnpm/@fastify+jwt@9.1.0/node_modules/@fastify/jwt/jwt.js:454:14)
    at Object.preValidation (/app/palmr-app/dist/modules/auth/routes.js:146:31)
    at hookIterator (/app/palmr-app/node_modules/.pnpm/fastify@5.4.0/node_modules/fastify/lib/hooks.js:408:10)
    at next (/app/palmr-app/node_modules/.pnpm/fastify@5.4.0/node_modules/fastify/lib/hooks.js:242:18)
    at hookRunner (/app/palmr-app/node_modules/.pnpm/fastify@5.4.0/node_modules/fastify/lib/hooks.js:264:5)
    at handler (/app/palmr-app/node_modules/.pnpm/fastify@5.4.0/node_modules/fastify/lib/handleRequest.js:66:7) {
  code: 'FST_JWT_NO_AUTHORIZATION_IN_COOKIE',
  statusCode: 401
}
```

`docker-compose.yaml`

```yaml
services:
  palmr:
    container_name: palmr
    image: kyantech/palmr
    restart: always
    ports:
      - 8000:5487
    volumes:
      - data:/app/server
    environment:
      SECURE_SITE: true

volumes:
  data:
```

My Palmr instance is being served by Caddy:

```Caddyfile
palmr.adamhl.dev {
  reverse_proxy palmr.lan:8000
}
```

**Comment by adamhl8** [comment]
Ah sorry, I probably should read the [docs](https://palmr.kyantech.com.br/docs/3.1-beta/reverse-proxy-configuration#configuration-options) more carefully :)

**Comment by adamhl8** [comment]
Nevermind, I'm not sure what the exact issue here is. By default, caddy sets the [necessary headers](https://caddyserver.com/docs/caddyfile/directives/reverse_proxy#defaults).

These are the cookies I see in local storage:

<img width="319" height="198" alt="Image" src="https://github.com/user-attachments/assets/b41f56b1-1fe3-4c55-a201-9b1131f8d08f" />

<img width="320" height="200" alt="Image" src="https://github.com/user-attachments/assets/270599fe-d0b2-480c-99b8-c846ede14667" />

<img width="319" height="199" alt="Image" src="https://github.com/user-attachments/assets/1fc172ab-a2e6-4d98-bc52-8add26773d68" />

**Comment by nealhead** [comment]
I have this problem with NGINX Proxy Manager as well... but it also happens directly to the local IP with secure site off.

```
FastifyError [Error]: No Authorization was found in request.cookies
    at lookupToken (/app/palmr-app/node_modules/.pnpm/@fastify+jwt@9.1.0/node_modules/@fastify/jwt/jwt.js:272:17)
    at _Request.requestVerify [as jwtVerify] (/app/palmr-app/node_modules/.pnpm/@fastify+jwt@9.1.0/node_modules/@fastify/jwt/jwt.js:487:15)
    at useGlobalOptions (/app/palmr-app/node_modules/.pnpm/@fastify+jwt@9.1.0/node_modules/@fastify/jwt/jwt.js:455:31)
    at new Promise (<anonymous>)
    at _Request.requestVerify [as jwtVerify] (/app/palmr-app/node_modules/.pnpm/@fastify+jwt@9.1.0/node_modules/@fastify/jwt/jwt.js:454:14)
    at Object.preValidation (/app/palmr-app/dist/modules/auth/routes.js:146:31)
    at hookIterator (/app/palmr-app/node_modules/.pnpm/fastify@5.4.0/node_modules/fastify/lib/hooks.js:408:10)
    at next (/app/palmr-app/node_modules/.pnpm/fastify@5.4.0/node_modules/fastify/lib/hooks.js:242:18)
    at hookRunner (/app/palmr-app/node_modules/.pnpm/fastify@5.4.0/node_modules/fastify/lib/hooks.js:264:5)
    at handler (/app/palmr-app/node_modules/.pnpm/fastify@5.4.0/node_modules/fastify/lib/handleRequest.js:66:7) {
  code: 'FST_JWT_NO_AUTHORIZATION_IN_COOKIE',
  statusCode: 401
```

**Comment by Datajoke** [comment]
I'm having the same type of error while downloading while using the link. I can download just fine from the admin dashboard.

Compose variable: `SECURE_SITE=true`
Nginx proxy manager advanced config: `proxy_set_header X-Forwarded-Proto $scheme;`
If I downgrade to v3.2.0-beta the issue disappears and recipients are able to download the file just fine.


`FastifyError [Error]: No Authorization was found in request.cookies

    at lookupToken (/app/palmr-app/node_modules/.pnpm/@fastify+jwt@9.1.0/node_modules/@fastify/jwt/jwt.js:272:17)

    at _Request.requestVerify [as jwtVerify] (/app/palmr-app/node_modules/.pnpm/@fastify+jwt@9.1.0/node_modules/@fastify/jwt/jwt.js:487:15)

    at useGlobalOptions (/app/palmr-app/node_modules/.pnpm/@fastify+jwt@9.1.0/node_modules/@fastify/jwt/jwt.js:455:31)

    at new Promise (<anonymous>)

    at _Request.requestVerify [as jwtVerify] (/app/palmr-app/node_modules/.pnpm/@fastify+jwt@9.1.0/node_modules/@fastify/jwt/jwt.js:454:14)

    at Object.preValidation (/app/palmr-app/dist/modules/file/routes.js:11:27)

    at hookIterator (/app/palmr-app/node_modules/.pnpm/fastify@5.4.0/node_modules/fastify/lib/hooks.js:408:10)

    at next (/app/palmr-app/node_modules/.pnpm/fastify@5.4.0/node_modules/fastify/lib/hooks.js:242:18)

    at hookRunner (/app/palmr-app/node_modules/.pnpm/fastify@5.4.0/node_modules/fastify/lib/hooks.js:264:5)

    at handler (/app/palmr-app/node_modules/.pnpm/fastify@5.4.0/node_modules/fastify/lib/handleRequest.js:66:7) {  code: 'FST_JWT_NO_AUTHORIZATION_IN_COOKIE',

**Comment by KristijanBoshev** [comment]
Going back to v3.2.0-beta resolved this problem for me...
My setup is behind Traefik ingress controller!

**Comment by radsto** [comment]
Hi, same issue here, setup is deployed on K8S behind a Cloud Native AWS ALB controller, rolling back to v3.2.0-beta works.

**Comment by advokat11** [comment]
How to rollback to v3.2.0-beta?

**Comment by radsto** [comment]
> How to rollback to v3.2.0-beta?

Just change the docker image tag ?

**Comment by leon-ITA** [comment]
Same error with caddy

`FastifyError [Error]: No Authorization was found in request.cookies

    at lookupToken (/app/palmr-app/node_modules/.pnpm/@fastify+jwt@9.1.0/node_modules/@fastify/jwt/jwt.js:272:17)

    at _Request.requestVerify [as jwtVerify] (/app/palmr-app/node_modules/.pnpm/@fastify+jwt@9.1.0/node_modules/@fastify/jwt/jwt.js:487:15)

    at useGlobalOptions (/app/palmr-app/node_modules/.pnpm/@fastify+jwt@9.1.0/node_modules/@fastify/jwt/jwt.js:455:31)

    at new Promise (<anonymous>)

    at _Request.requestVerify [as jwtVerify] (/app/palmr-app/node_modules/.pnpm/@fastify+jwt@9.1.0/node_modules/@fastify/jwt/jwt.js:454:14)

    at Object.preValidation (/app/palmr-app/dist/modules/file/routes.js:11:27)

    at hookIterator (/app/palmr-app/node_modules/.pnpm/fastify@5.4.0/node_modules/fastify/lib/hooks.js:408:10)

    at next (/app/palmr-app/node_modules/.pnpm/fastify@5.4.0/node_modules/fastify/lib/hooks.js:242:18)

    at hookRunner (/app/palmr-app/node_modules/.pnpm/fastify@5.4.0/node_modules/fastify/lib/hooks.js:264:5)

    at handler (/app/palmr-app/node_modules/.pnpm/fastify@5.4.0/node_modules/fastify/lib/handleRequest.js:66:7) {

  code: 'FST_JWT_NO_AUTHORIZATION_IN_COOKIE',

  statusCode: 401

}`

**Comment by shawnvanderveer** [comment]
To solve the issue SECURE_SITE=true when using Caddy, NGINX, Traefik etc.
After that make sure your url is reachable with https, so use something like lets encrypt. 

After that rebuild the whole thing

**Comment by danielalves96** [comment]
Hey! Probably fixed in the version `v3.3.0-beta`, we recommend following the migration guide to the new version: https://github.com/kyantech/Palmr/discussions/348

Could they conduct another test?

**Comment by Dim145** [comment]
I still have the same problem on version 3.3.1-beta.
I am using nginx proxy manager as a reverse proxy.

**Comment by Dim145** [comment]
After analysis, if someone is not logged in (for a reverse share, for example), cookies are not sent to the backend. This is when the error ‘FST_JWT_NO_AUTHORIZATION_IN_COOKIE’ appears.

**Comment by Dim145** [comment]
After analysing the source code, the problem is that multipart uploads must be performed by logged-in users.
This comes from these lines:
In the file `server/src/modules/file/routes.ts`:
```js
app.get(
    "/files/multipart/part-url",
    {
      preValidation,
      ....
```
The ‘preValidation’ method attempts to look at the JWT, but it is not present in a reverse share context.
This is the case for all multipart upload routes (create, complete, abort, and part-url).

In the `server/src/modules/file/controller.ts` file:
```js
const userId = (request as any).user?.userId;
if (!userId) {
  return reply.status(401).send({ error: "Unauthorized" });
}
```
The user ID check fails because people using reverse-share are not logged in...
Obviously, this is also the case for all multipart upload methods as above.

In a test environment, I tried simply disabling these lines (comments), and the upload works fine. However, this is not secure...

I imagine that the problem cannot be easily solved without removing the road safety measures.

**Comment by danielalves96** [comment]
Fixed in the version `v3.3.2-beta`
