### ISSUE TITLE
Upload fails behind nginx

### ISSUE THREAD

**Issue by YgzNsl** [kyantech/Palmr#258]
I have a docker container running with container name "palmr".
And I'm running palmr behind nginx. Here is my nginx conf for palmr:

location / {
    client_max_body_size 5G;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_pass http://palmr:5487;
}

However, one of the upload methods (PUT) throws 500.

<img width="1354" height="114" alt="Image" src="https://github.com/user-attachments/assets/2af49e2a-4da6-4263-ad75-6328b4a914fa" />

<img width="938" height="351" alt="Image" src="https://github.com/user-attachments/assets/44f3b2b4-cc69-47a5-9c58-70170cda97b3" />

**Comment by bawahakim** [comment]
I've had a similar issue (500 internal server error) and no logs. What seems to have fixed it is setting the uploads and temp-uploads folder owner to `node` https://github.com/kyantech/Palmr/issues/256#issuecomment-3292405760

**Comment by eriklysoe** [comment]
Same problem using cloudflare

**Comment by bawahakim** [comment]
https://github.com/kyantech/Palmr/pull/273

This should fix the cloudflare issue behind proxy

**Comment by YgzNsl** [comment]
> I've had a similar issue (500 internal server error) and no logs. What seems to have fixed it is setting the uploads and temp-uploads folder owner to `node` [#256 (comment)](https://github.com/kyantech/Palmr/issues/256#issuecomment-3292405760)

I tried this and it won't work. Still throws 500 internal server error.

**Comment by danielalves96** [comment]
Hey! Probably fixed in the version `v3.3.1-beta`, we recommend following the migration guide to the new version: https://github.com/kyantech/Palmr/discussions/348

Could they conduct another test?

**Comment by YgzNsl** [comment]
Latest version fixed it.
