### ISSUE TITLE
Bug Report: Large File Upload Failure (10GB+)

### ISSUE THREAD

**Issue by danimr** [kyantech/Palmr#304]
### Description
File uploads larger than 10GB fail when attempting to upload to S3-compatible storage (Wasabi). The upload request returns a `400 Bad Request` error from the S3 bucket.

### Environment
- **Version**: v3.2.3-beta (docker image)
- **File Size**: 11.77 GB (11,769,080,326 bytes)
- **File Name**: `backup_2509270236_2510030236.tar.zip`
- **File Extension**: `.zip`
- **Storage Backend**: Wasabi S3 (eu-west-2 region)
- **Date/Time**: October 15, 2025, 19:04:25 GMT

### Configuration
```env
NEXT_PUBLIC_UPLOAD_CHUNK_SIZE_MB=150
MAX_FILESIZE=21474836480  # 20GB
```

### Steps to Reproduce
1. Configure the application with the environment variables listed above
2. Attempt to upload a file larger than 10GB (tested with 11.77GB zip file)
3. Observe the upload process through browser DevTools

### Expected Behavior
The file should upload successfully to the S3 bucket.

### Actual Behavior
The upload fails with a `400 Bad Request` error from the S3 bucket.

#### Request Flow
1. **File Check Request** (201)
   - Endpoint: `POST /api/files/check`
   - Response time: 66ms
   
2. **Presigned URL Request** (200)
   - Endpoint: `GET /api/files/presigned-url?filename=0KLd9pewAHOD&extension=zip`
   - Response time: 61ms
   
3. **S3 Upload Request** (400)
   - Endpoint: `PUT https://dock01-files.s3.eu-west-2.wasabisys.com/...`
   - Response: `400 Bad Request`
   - Response time: 1,031ms

#### Error Response Headers
```
Status: 400 Bad Request
Server: WasabiS3/7.23.5268-2025-08-15-bac279dac0
Content-Type: application/xml
x-amz-request-id: CA81C814FA750F45:B
```

#### Presigned URL Parameters
```
X-Amz-Algorithm=AWS4-HMAC-SHA256
X-Amz-Content-Sha256=UNSIGNED-PAYLOAD
X-Amz-Expires=21600 (6 hours)
x-amz-checksum-crc32=AAAAAA==
x-amz-sdk-checksum-algorithm=CRC32
```

### Observations
- The file size (11.77GB) is below the configured `MAX_FILESIZE` of 20GB
- The presigned URL request returned 200 OK
- The S3 PUT request returned 400 Bad Request
- The HAR file shows `bodySize: 0` for the PUT request
- The `x-amz-checksum-crc32` value is `AAAAAA==` (base64 decodes to all zeros)

**Comment by horschdel** [comment]
I am having the same issue, but with a file about 9,7GB while the settings should allow files up to 100GB.

**Comment by danimr** [comment]
Taking a look into the code, it looks like that when the storage is S3 the chunking system is not used, and therefore the limit of 5GB still applies.  But not sure; let's see what the devs say.

**Comment by danielalves96** [comment]
Hey! Probably fixed in the version v3.3.0-beta, we recommend following the migration guide to the new version: https://github.com/kyantech/Palmr/discussions/348

Could they conduct another test?

**Comment by pedorich-n** [comment]
I'm not sure if I'm experiencing exactly the same issue, but I see similar symptoms. I'm trying to setup Palmr with Cloudflare R2 and my upload requests fail with response 400. 

What led me to this issue is `"x-amz-checksum-crc32": "AAAAAA=="` & `"x-amz-sdk-checksum-algorithm": "CRC32"` in the headers. After checking the docs I found R2 doesn't support CRC-32 for full objects: https://developers.cloudflare.com/r2/api/s3/api/#checksum-types. 
I know ultimately it's Cloudflare's problem for not providing the full(er) support with S3 API, but maybe https://github.com/kyantech/Palmr/pull/324 was another solution?

**Comment by danimr** [comment]
worked great in the last beta! thank you very much.

**Comment by danielalves96** [comment]
Probably fixed in the version `v3.3.2-beta`, Could they conduct another test?

**Comment by pedorich-n** [comment]
I'm still seeing the same response.
I'll raise another issue, since my problem seems more provider-specific.
