### ISSUE TITLE
Shared folder not auto add new files

### ISSUE THREAD

**Issue by wrdmarco** [kyantech/Palmr#339]
If i share a folder newly added files wil not be auto added to share.

**Comment by danielalves96** [comment]
Hey! Probably fixed in the version `v3.3.0-beta`, we recommend following the migration guide to the new version: https://github.com/kyantech/Palmr/discussions/348

Could you conduct another test?

**Comment by wrdmarco** [comment]
Just tested but unfortunately still not working. I shared a folder but after sharing the folder newly added files are not added in already shared folder

**Comment by danielalves96** [comment]
@wrdmarco I'll investigate the problem further! I was focused on the major upload and download refactoring, which consumed a lot of development time, but now I can focus more on this issue. Thanks for the report!
