### ISSUE TITLE
[Bug] Share UI somewhat broken

### ISSUE THREAD

**Issue by ruohki** [kyantech/Palmr#91]
Hey,
when fiddling with shares i noticed two things.

1. View Details and Generate Link are not working / without any functionality.

<img width="206" alt="Image" src="https://github.com/user-attachments/assets/261b5653-49f1-415e-a19d-7dbb335c89a1" />

2. Editing the Share opens up an upload window infront of the Edit Dialog. Closing the upload dialog will also close the edit dialog

<img width="635" alt="Image" src="https://github.com/user-attachments/assets/f7004b95-6ced-49b4-9103-050675cf9e71" />

Am on this morning latest version

**Comment by danielalves96** [comment]
Hey!

I just tested with the latest version `v3.0.0-beta.9`, the same one available in the current `latest` version, which I just generated a few minutes ago and I have not had any of the issues listed. Both reports you monitor above work perfectly on both local and VPS environments for me. Could you please update and confirm if there are still bugs?

**Comment by danielalves96** [comment]
@ruohki 
here in my VPS server:
https://github.com/user-attachments/assets/d5456dd8-f13d-46aa-bc35-f40d52125597
https://github.com/user-attachments/assets/bb5dcfe4-0245-4453-a582-e0ebbc5a297d

**Comment by ruohki** [comment]
ill try to pull latest and test later

**Comment by ruohki** [comment]
So Details and Link still dont work for me. No console errors. Did a cache free reload. Am on latest as of right now.

Browser is Brave:latest

**Comment by GonzagueGB** [comment]
Same problem, with latest version and not working on Edge, Chrome, Firefox (PC) and Safari.

**Comment by danielalves96** [comment]
@ruohki @GonzagueGB Hey everyone,

I'm writing to let you know that I've just released version `v3.1.0-beta`, which likely addresses the bug. If you could update, retest, and provide feedback, I'd appreciate it.

Note: If you're using OIDC authentication, this release will clear your existing OIDC data. You'll need to reconfigure it, as the update involved structural changes to support additional authentication providers.

**Comment by ruohki** [comment]
Sadly, my server is currently down and I can't test. But will asap

**Comment by GonzagueGB** [comment]
@danielalves96 partially fixed for me. 

What it is not working are

- Copy link
- Edit link

Also but pulling you latest image broke what I fixed here https://github.com/kyantech/Palmr/issues/52#issuecomment-3002651901 

You really need to have serious look at your compose...

**Comment by danielalves96** [comment]
Hey, @GonzagueGB  thanks for the feedback.

I've been actively working to fix as many issues as possible, but as a solo developer, it's really challenging to guarantee 100% functionality across all the countless environments out there, especially when dealing with setups.

We're still in beta, and this phase is exactly where these kinds of inconsistencies are expected and needed so they can be addressed. I understand that regressions are frustrating, but it’s part of the process when pushing improvements forward. If the latest image introduced issues on your end, the previous version is still available and stable to fall back on.

Still, I appreciate you taking the time to test things and point out what's not working, even if it stings a bit, it helps me try to make this better every day. I know it's not perfect yet, and I wish I could move faster, but I'm doing my best.

Thanks again.

**Comment by GonzagueGB** [comment]
Don't take my comment in a bad way, just stating a fact that this should be fixed. Many people will not even bother posting a comment/feedback here and will never come back, which I believe pity seeing the potential of this soft.

Good luck.
